### ISSUE TITLE
Process all variable declarations before assignment

### ISSUE THREAD

**Issue by emmaneugene** [emmaneugene/CS4215-sourClang-VM#8]
Given that variables with a specific name can only be declared once in a scope, it should be possible to process all variable declarations in a single pass through the source code before further operations (assignments, operators, etc.). This could be considered as a preprocessing step that simplifies the role of the evaluator as well.

```c
int main() {
    int x = 2;
    char x = 'a'; // compile error
}
```

```c
int main() {
    int x = 2;
    {
        char x = 'a'; // No conflict, x within a new scope
    }
}
```

**Comment by jieffyy** [comment]
Done!
